# Generated by Django 2.1.5 on 2019-02-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190219_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('post_id', 'user_id')},
        ),
    ]
