# Generated by Django 2.1.5 on 2019-02-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190219_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
    ]
